# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weather-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weather-ios
  pod 'NMapsMap'
  pod 'Alamofire'
  pod 'SnapKit'
end
